# -*- coding: utf-8 -*-
"""ClientOn_v1-0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUAJ_nFMbcPHrr3ifWEGjgfPVkrx0AR8
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

# Configura a API Key do Google Gemini

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

# Configura o cliente da SDK do Gemini

from google import genai

client = genai.Client()

MODEL_ID = "gemini-2.0-flash"

# Instalar Framework de agentes do Google ################################################
!pip install -q google-adk

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import warnings

warnings.filterwarnings("ignore")

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

##########################################
# -- Agente 1: Buscador de Informações -- #
##########################################
def agente_buscador(topico, data_de_hoje):

    buscador = Agent(
        name="agente_buscador",
        model="gemini-2.0-flash",
        instruction="""
        Você é um assistente de pesquisa especializado em due diligence de empresas.
        Sua tarefa é realizar uma investigação abrangente sobre a reputação e histórico da empresa indicada em topico.
        Para isso, utilize a ferramenta de busca do Google (google_search) para:
        - Identificar informações básicas da empresa:
        CNPJ, data de fundação/tempo de existência, endereço, nicho de mercado principal e outras informações cadastrais relevantes.
        - Consultar a reputação online:
        Buscar e analisar avaliações e reclamações sobre a empresa em topico no site Reclame Aqui (reclameaqui.com.br).
        Explorar outras plataformas de avaliação de consumidores e reputação de empresas (se disponíveis e relevantes para o contexto brasileiro).
        Investigar comentários em redes sociais da empresa ou sobre a empresa em topico.
        - Buscar notícias sobre a empresa em topico, fotos e avaliações no API Places do Google.
        - Verificar pendências legais e regulatórias:
        Pesquisar por processos judiciais e menções da empresa em topico no Jusbrasil e sites jurídicos oficiais.
        Verificar a existência de reclamações ou processos administrativos contra a empresa em topico
        no Procon e outros órgãos reguladores relevantes para o nicho da empresa.
        Formato: Você vai realizar toda essa pesquisa, mas só vai mostrar as informações básicas e fundamentais neste passo, em formato tabulado.
        """,
        description="Agente que busca informações no Google",
        tools=[google_search]
    )

    entrada_do_agente_buscador = f"Empresa: {topico}\nData de hoje: {data_de_hoje}"

    lancamentos = call_agent(buscador, entrada_do_agente_buscador)
    return lancamentos

################################################
# --- Agente 2: Avaliador de reputação --- #
################################################
def agente_avaliador(topico, lancamentos_buscados):
    avaliador = Agent(
        name="agente_avaliador",
        model="gemini-2.0-flash", #não foi possível usar um modelo mais avançado, mas seria o ideal

        # Inserir as instruções do Agente Avaliador #################################################
        instruction="""
        Você é um orientador de consumidores especializado em due diligence de empresas.
        Com base em
        1 - nas informações levantadas pelo agente buscador, e/ou
        2 - na análise dos requisitos de segurança do link indicado em tópico, se for um link
        (Caso o usuário peça informações a partir de um link, realize as ações anteriores cabíveis e também:
        - Identifique se o link é seguro.
        - Identifique se o link é de propriedade da empresa sugerida.
        - Verifique os selos de segurança do site, a política de privacidade, certificado SSL e outros critérios de segurança
        que ajudem a evitar que o usuário caia em um golpe.),
        você deve:
        - Usar a ferramenta de busca do Google (google_search) para indicar se a empresa é confiável ou não e
        elaborar uma justificativa para a afirmação, de maneira sucinta, linguagem clara e acessível.
        - Se possível, categorize os tipos de reclamações ou avaliações
        (por exemplo, problemas com produto, atendimento, entrega) para fornecer uma visão mais detalhada da reputação.
        - Mencione a data dos principais comentários e categorize como "Elogio", "Reclamação" ou "Neutro".
        Destaque a informação desse agente em relação aos outros, pois é a mais importante.
        Destaque a conclusão sobre a empresa ou site ser confiável ou não colocando as expressões "É CONFIÁVEL" ou "NÃO É CONFIÁVEL"
        em negrito e caixa alta, esta informação deve estar na primeira linha do texto.
        Formato: As informações devem ser sucintas, com linguagem clara e acessível, apresentadas de  modo tabulado
        com os dados positivos em verde e os negativos em vermelho.
        """,
        description="Agente que avalia a confiabilidade da empresa",
        tools=[google_search]
    )

    entrada_do_agente_avaliador = f"Tópico:{topico}\nLançamentos buscados: {lancamentos_buscados}"
    # Executa o agente
    avaliacao_da_empresa = call_agent(avaliador, entrada_do_agente_avaliador)
    return avaliacao_da_empresa

######################################
# --- Agente 3: Consultor --- #
######################################
def agente_consultor(topico, avaliacao_da_empresa):
    consultor = Agent(
        name="agente_consultor",
        model="gemini-2.0-flash",
        instruction="""
            Você é um consultor de consumidores, com foco em oferecer respostas claras e concisas para ajudá-los
            no consumo consciente e seguro diante da escolha de uma empresa.
            Com base nas informações dos lacamentos_buscados e avaliacao_da_empresa, você deve:
            - Considerar o tom geral das avaliações e reclamações encontradas pelo agente_buscador e agente_avaliador.
            - Indicar ao cliente se deve ou não negociar com a empresa ou comprar um produto dela.
            - Indicar para qual público e finalidade a empresa é indicada.
            - Se cabível, indicar aspectos de responsabilidade social, compliance, sustentabilidade e
            outras práticas que forem um diferencial da empresa.
            - Se a empresa for CONFIÁVEL: mencionar pontos positivos mais relevantes com base na recorrência do tema nas avaliações.
            - Se cabível, indicar concorrente para comparação, apenas se tiver qualidades compatíveis ou superiores às da empresa pesquisada.
            - Compare a reputação da empresa consultada com a média do setor, se houver dados disponíveis.
            - Considere que empresas sem informações cadastrais online, como CNPJ, não são confiáveis.
            Formato: Essa conclusão deve ser sucinta, com linguagem clara e acessível, ser tabulada, os dados positivos em verde e os negativos em vermelho.
            """,
        description="Agente consultor de negocios com foco no cliente"
    )
    entrada_do_agente_consultor = f"Tópico: {topico}\nPlano de post: {avaliacao_da_empresa}"
    # Executa o agente
    decisao_consumidor = call_agent(consultor, entrada_do_agente_consultor)
    return decisao_consumidor

data_de_hoje = date.today().strftime("%d/%m/%Y")

print("🧐 Iniciando o Sistema de Avaliação de Confiança de Empresas 🧐")

# --- Obter o Tópico do Usuário ---
topico = input("Digite o link do site ou o nome da empresa sobre a qual você deseja informações: ")

# Inserir lógica do sistema de agentes ################################################
if not topico:
    print("Você esqueceu de digitar o tópico!")
else:
    print(f"Maravilha! Vamos saber mais sobre a empresa {topico}")

    lancamentos_buscados = agente_buscador(topico, data_de_hoje)
    print("\n--- 📝 Informações sobre a empresa ---\n")
    display(to_markdown(lancamentos_buscados))
    print("--------------------------------------------------------------")

    avaliacao_da_empresa = agente_avaliador(topico, lancamentos_buscados)
    print("\n---❓Análise de confiança ---\n")
    display(to_markdown(avaliacao_da_empresa))
    print("--------------------------------------------------------------")

    decisao_consumidor = agente_consultor(topico, avaliacao_da_empresa)
    print("\n--- 👨‍⚖️ Sugestão de decisão para o consumidor ---\n")
    display(to_markdown(decisao_consumidor))
    print("--------------------------------------------------------------")